fn main() {
    #[cfg(target_os = "windows")]
    {
        println!(
            "cargo:rustc-link-search=C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.4\\lib\\x64"
        );
    }
    #[cfg(not(target_os = "windows"))]
    {
        println!("cargo:rustc-link-search=/usr/local/cuda-13.0/targets/x86_64-linux/lib/stubs");
        println!("cargo:rustc-link-search=/usr/local/cuda-13.0/targets/x86_64-linux/lib");
    }

    println!("cargo:rustc-link-lib=cuda");
    println!("cargo:rustc-link-lib=cudart");
    // println!("cargo:rustc-link-lib=static=nppicc_static");
    println!("cargo:rustc-link-lib=nppc");
    println!("cargo:rustc-link-lib=nppicc");

    println!("cargo:rustc-link-lib=dylib=avcodec");
    println!("cargo:rustc-link-lib=dylib=avdevice");
    println!("cargo:rustc-link-lib=dylib=avfilter");
    println!("cargo:rustc-link-lib=dylib=avformat");
    println!("cargo:rustc-link-lib=dylib=avutil");
    println!("cargo:rustc-link-lib=dylib=swresample");
    println!("cargo:rustc-link-lib=dylib=swscale");

    // println!("cargo:rustc-link-lib=dylib=nppial");
    // println!("cargo:rustc-link-lib=dylib=nppidei");
    // println!("cargo:rustc-link-lib=dylib=nppif");
    // println!("cargo:rustc-link-lib=dylib=nppig");
    // println!("cargo:rustc-link-lib=dylib=nppim");
    // println!("cargo:rustc-link-lib=dylib=nppist");
    // println!("cargo:rustc-link-lib=dylib=nppisu");
    // println!("cargo:rustc-link-lib=dylib=nppitc");
    // println!("cargo:rustc-link-lib=dylib=npps");
    // #[cfg(target_os = "windows")]
    // {
    //     println!("cargo:rustc-link-arg=-Wl,-rpath,D:/msys64/temp/bin");
    // }

    // ================================> 暴露自己lib
    let crate_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let package_name = std::env::var("CARGO_PKG_NAME").unwrap();

    let mut config = cbindgen::Config::default();
    config.language = cbindgen::Language::C;
    // config.include_guard = Some(format!("{}_H", package_name.to_uppercase()));
    config.autogen_warning = Some("/* AUTO-GENERATED by cbindgen */".to_string());
    config.parse = cbindgen::ParseConfig {
        parse_deps: false,
        include: Some(vec!["api".into()]),
        ..Default::default()
    };
    config.export = cbindgen::ExportConfig {
        include: vec![
            "init_image_demo".into(),
            "register_image_demo_texture".into(),
            "draw_image_demo_texture".into(),
            "destroy_image_demo".into(),
            "run_image_app".into(),
            "init_player".into(),
            "get_ratios".into(),
            "register_textures".into(),
            "unregister_textures".into(),
            "start_player".into(),
            "load_frames".into(),
            "draw_frames".into(),
            // "recycle_frames".into(),
            "pause_player".into(),
            "stop_player".into(),
            "terminate_player".into(),
            "init_logger".into(),
            "mock_video_player".into(),
            "UnityRenderThreadEventData".into(),
            "GetRegisterEventFunc".into(),
            "GetUnRegisterEventFunc".into(),
            "GetDrawEventFunc".into(),
            "UnityParam".into(),
        ],
        exclude: vec![
            "cudaMalloc".into(),
            "cudaMallocPitch".into(),
            "cudaFree".into(),
            "cudaMemcpy".into(),
            "cudaMemset2D".into(),
            "cudaStreamSynchronize".into(),
            "nppGetStreamContext".into(),
            "nppiNV12ToRGB_8u_P2C3R_Ctx".into(),
            "cudaGraphicsGLRegisterImage".into(),
            "cudaGraphicsD3D11RegisterResource".into(),
            "cudaGraphicsUnregisterResource".into(),
            "cudaGraphicsMapResources".into(),
            "cudaGraphicsSubResourceGetMappedArray".into(),
            "cudaMemcpy2DToArray".into(),
            "cudaGraphicsUnmapResources".into(),
            "cudaDeviceSynchronize".into(),
            "cudaMemcpy2D".into(),
            "CUDA_MEMCPY_HOST_TO_HOST".into(),
            "CUDA_MEMCPY_HOST_TO_DEVICE".into(),
            "CUDA_MEMCPY_DEVICE_TO_HOST".into(),
            "CUDA_MEMCPY_DEVICE_TO_DEVICE".into(),
        ],
        ..Default::default()
    };
    let output_file = std::path::PathBuf::from(&crate_dir)
        .join("output")
        .join(format!("{}.h", package_name));

    cbindgen::generate_with_config(&crate_dir, config)
        .unwrap()
        .write_to_file(&output_file);
    // // println!("cargo:rerun-if-changed=src/lib.rs");
    // println!("cargo:rerun-if-changed=src/ffi.rs");

    // ================================> 引入外部lib
    // Tell cargo to invalidate the built crate whenever the wrapper changes

    // The bindgen::Builder is the main entry point
    // to bindgen, and lets you build up options for
    // the resulting bindings.
    // let bindings = bindgen::Builder::default()
    //     // The input header we would like to generate
    //     // bindings for.
    //     .header("./includes/wrapper.h")
    //     // Tell cargo to invalidate the built crate whenever any of the
    //     // included header files changed.
    //     // .parse_callbacks(Box::new(bindgen::CargoCallbacks))
    //     // Finish the builder and generate the bindings.
    //     // .clang_arg("-xc++")
    //     // .clang_arg("-std=c++12")
    //     // .clang_arg(format!("-I/usr/include/c++/11"))
    //     // .clang_arg(format!("-I/usr/include/x86_64-linux-gnu/c++/11"))
    //     .generate()
    //     // Unwrap the Result and panic on failure.
    //     .expect("Unable to generate bindings");

    // // Write the bindings to the $OUT_DIR/bindings.rs file.
    // // let out_path = PathBuf::from(env::var("OUT_DIR").unwrap());
    // bindings
    //     .write_to_file("./src/bindings.rs")
    //     .expect("Couldn't write bindings!");
}
