/* AUTO-GENERATED by cbindgen */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#define CUDA_GRAPHIC_REGISTER_FLAG_SURFACE_LOAD_STORE 4

#define CHANNEL_SIZE 10

#define AUDIO_SAMPLES 1024

#define AUDIO_MAX_DELAY 50

typedef void (*UnityRenderThreadEventData)(int, void *);

typedef struct UnityParam
{
  void *const *texture_rgba_ids;
  int length;
  const void *handle;
  int code;
} UnityParam;

/**
 * 初始化日志
 */
void init_logger(const char *logger, int clear);

/**
 * 初始化播放器
 */
const void *init_player(const char *const *video_paths, int length);

/**
 * 获取播放源分辨率
 */
int get_ratios(int *widths, int *heights, int length, const void *player);

/**
 * 注册texture
 */
void register_textures(int _evt_id, void *param);

/**
 * 反注册texture，在停止前需要执行，避免异常
 */
void unregister_textures(int _evt_id, void *param);

/**
 * 启动播放器 = 启动解码 + 同步队列
 */
int start_player(const void *player);

/**
 * 加载帧播放序列，该序列必须为对齐的帧
 */
int load_frames(const void *player);

/**
 * 绘制播放帧序列，必须在[load_frames]之后, 这时应该已经使用过 [gl.bind_texture]，在使用该方法之后，应用应该启动着色器工作也就是 [gl.draw_arrays]
 */
void draw_frames(int _evt_id,
                 void *param);

/**
 * 回收播放帧序列，将[load_frames]得到的数据放回到缓存队列中，用于后续解码使用，节约内存和显存
 * 播控，暂停，再次触发则恢复播放态，播控操作不建议1秒内频繁操作
 */
int pause_player(const void *player);

/**
 * 停止播放 = 解码结束 + 同步结束， 仅代表播放状态，不能代表gpu资源安全回收
 */
int stop_player(const void *player);

/**
 * 销毁播放器 = 等待解码线程flush， 阻塞，完成后gpu资源安全回收
 */
int terminate_player(const void *player);

/**
 * 销毁播放器 = 等待解码线程flush， 阻塞，完成后gpu资源安全回收
 */
int mock_video_player(int32_t type_,
                      uintptr_t view_ports,
                      const char *media_path,
                      const void *(*init_player)(const char *const *video_paths, int length),
                      int (*get_ratios)(int *widths, int *heights, int length, const void *player),
                      void (*register_textures)(int _evt_id, void *param),
                      void (*unregister_textures)(int _evt_id, void *param),
                      int (*start_player)(const void *player),
                      int (*pause_player)(const void *player),
                      int (*load_frames)(const void *player),
                      void (*draw_frames)(int _evt_id, void *param),
                      int (*stop_player)(const void *player),
                      int (*terminate_player)(const void *player));

UnityRenderThreadEventData GetRegisterEventFunc(void);

UnityRenderThreadEventData GetUnRegisterEventFunc(void);

UnityRenderThreadEventData GetDrawEventFunc(void);
