/* AUTO-GENERATED by cbindgen */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

const void *init_demo(const char *path,
                      int width,
                      int height,
                      unsigned int tex_y_id,
                      unsigned int tex_uv_id);

int register_demo_texture(unsigned int tex_y_id, unsigned int tex_uv_id, const void *handle);

void destroy_demo(const void *handle);
